### ISSUE TITLE
Incompatible Log4J version

### ISSUE THREAD

**Issue by ForceUpdate1** [rfoltyns/log4j2-elasticsearch#34]
I tried adding the appender to the Minecraft logger

Minecraft Log4J Version log4j-core:2.8.1

`
[15:35:35 ERROR]: [org.bukkit.craftbukkit.v1_15_R1.CraftServer] tried to access class org.apache.logging.log4j.core.jackson.StackTraceElementMixIn from class org.apache.logging.log4j.core.jackson.ExtendedLog4j2JsonModule initializing ElasticSearchAppender v1.0 (Is it up to date?)
java.lang.IllegalAccessError: tried to access class org.apache.logging.log4j.core.jackson.StackTraceElementMixIn from class org.apache.logging.log4j.core.jackson.ExtendedLog4j2JsonModule
at org.apache.logging.log4j.core.jackson.ExtendedLog4j2JsonModule.setupModule(ExtendedLog4j2JsonModule.java:37) ~[?:?]
at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:745) ~[?:?]
at org.appenders.log4j2.elasticsearch.JacksonJsonLayout$Builder.createConfiguredWriter(JacksonJsonLayout.java:122) ~[?:?]
at org.appenders.log4j2.elasticsearch.JacksonJsonLayout$Builder.build(JacksonJsonLayout.java:114) ~[?:?]
at de.cytooxien.elasticsearch.ElasticSearchPlugin.createElasticsearchAppenderBuilder(ElasticSearchPlugin.java:117) ~[?:?]
at de.cytooxien.elasticsearch.ElasticSearchPlugin.onLoad(ElasticSearchPlugin.java:44) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:361) ~[patched_1.15.1.jar:git-Paper-48]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.15.1.jar:git-Paper-48]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-48]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
`

    public void onLoad() {
        instance = this;
        Logger logger = LogManager.getLogger();
        org.apache.logging.log4j.core.Logger coreLogger = (org.apache.logging.log4j.core.Logger)logger;
        createLoggerProgrammatically(coreLogger, createElasticsearchAppenderBuilder(coreLogger, false, false), Configuration::getAsyncLoggerConfigDelegate);
    }

    public  ElasticsearchAppender.Builder createElasticsearchAppenderBuilder(org.apache.logging.log4j.core.Logger coreLogger, boolean messageOnly, boolean buffered) {

        JestHttpObjectFactory.Builder jestHttpObjectFactoryBuilder;
        if (buffered) {
            jestHttpObjectFactoryBuilder = BufferedJestHttpObjectFactory.newBuilder();

            int estimatedBatchSizeInBytes = BATCH_SIZE * INITIAL_ITEM_SIZE_IN_BYTES;

            ((BufferedJestHttpObjectFactory.Builder)jestHttpObjectFactoryBuilder).withItemSourceFactory(
                    PooledItemSourceFactory.newBuilder()
                            .withPoolName("batchPool")
                            .withInitialPoolSize(INITIAL_BATCH_POOL_SIZE)
                            .withItemSizeInBytes(estimatedBatchSizeInBytes)
                            .withMonitored(true)
                            .withMonitorTaskInterval(10000)
                            .build()
            );
        } else {
            jestHttpObjectFactoryBuilder = JestHttpObjectFactory.newBuilder();
        }

        jestHttpObjectFactoryBuilder.withConnTimeout(1000)
                .withReadTimeout(10000)
                .withIoThreadCount(8)
                .withDefaultMaxTotalConnectionPerRoute(8)
                .withMaxTotalConnection(8)
                .withMappingType("_doc");

        jestHttpObjectFactoryBuilder.withServerUris(hostname);

        IndexTemplate indexTemplate = new IndexTemplate.Builder()
                .withName("log4j2_test_jest")
                .withSource(loadClasspathResource("classpath:indexTemplate.json"))
                .build();

        BatchDelivery asyncBatchDelivery = new SpigotAsyncBatchDelivery(BATCH_SIZE + ADDITIONAL_BATCH_SIZE, 1000, jestHttpObjectFactoryBuilder.build(), AsyncBatchDelivery.Builder.DEFAULT_FAILOVER_POLICY, indexTemplate);

        IndexNameFormatter indexNameFormatter = RollingIndexNameFormatter.newBuilder()
                .withIndexName("log4j2_test_jest")
                .withPattern("yyyy-MM-dd-HH")
                .build();

        JacksonJsonLayout.Builder layoutBuilder = JacksonJsonLayout.newBuilder();

        if (buffered) {
            PooledItemSourceFactory sourceFactoryConfig = PooledItemSourceFactory.newBuilder()
                    .withPoolName("itemPool")
                    .withInitialPoolSize(INITIAL_ITEM_POOL_SIZE)
                    .withItemSizeInBytes(INITIAL_ITEM_SIZE_IN_BYTES)
                    .withMonitored(true)
                    .withMonitorTaskInterval(10000)
                    .build();
            layoutBuilder.withItemSourceFactory(sourceFactoryConfig).build();
        }

        return ElasticsearchAppender.newBuilder()
                .withName("elastic-appender")
                .withMessageOnly(messageOnly)
                .withBatchDelivery(asyncBatchDelivery)
                .withIndexNameFormatter(indexNameFormatter)
                .withLayout(layoutBuilder.build())
                .withIgnoreExceptions(false);
    }

    private String loadClasspathResource(String path) {
        try {
            BufferedReader br = new BufferedReader(new InputStreamReader(instance.getClassLoader().getResourceAsStream(path.replace("classpath:", "")), "UTF-8"));
            StringBuilder sb = new StringBuilder();

            String line;
            while((line = br.readLine()) != null) {
                sb.append(line);
                sb.append('\n');
            }

            return sb.toString();
        } catch (Exception var4) {
            throw new ConfigurationException(var4.getMessage(), var4);
        }
    }

    public void createLoggerProgrammatically(org.apache.logging.log4j.core.Logger coreLogger, ElasticsearchAppender.Builder appenderBuilder, Function<Configuration, AsyncLoggerConfigDelegate> delegateSupplier) {

        LoggerContext ctx = coreLogger.getContext();

        final Configuration config = ctx.getConfiguration();

        Appender appender = appenderBuilder.build();
        appender.start();

        ((LifeCycle)delegateSupplier.apply(config)).start();

        config.addAppender(appender);
    }

    public class SpigotAsyncBatchDelivery extends AsyncBatchDelivery {

        public SpigotAsyncBatchDelivery(int batchSize, int deliveryInterval, ClientObjectFactory objectFactory, FailoverPolicy failoverPolicy, IndexTemplate indexTemplate) {
            super(batchSize, deliveryInterval, objectFactory, failoverPolicy, indexTemplate);
        }

        @Override
        protected BatchEmitterServiceProvider createBatchEmitterServiceProvider() {
            return new SpigotBatchEmitterServiceProvider();
        }
    }

    public class SpigotBatchEmitterServiceProvider extends BatchEmitterServiceProvider{

        private final Logger LOG = StatusLogger.getLogger();

        @Override
        public BatchEmitter createInstance(int batchSize, int deliveryInterval, ClientObjectFactory clientObjectFactory, FailoverPolicy failoverPolicy) {
            BatchEmitterFactory factory = new BulkEmitterFactory(); //Service#load not supported
            LOG.info("BatchEmitterFactory class found {}", factory.getClass().getName());
            if (factory.accepts(clientObjectFactory.getClass())) {
                LOG.info("Using {} as BatchEmitterFactoryProvider", factory);
                return factory.createInstance(batchSize, deliveryInterval, clientObjectFactory, failoverPolicy);
            }
            throw new ConfigurationException(String.format("No compatible BatchEmitter implementations for %s found", clientObjectFactory.getClass().getName()));
        }
    }

**Comment by rfoltyns** [comment]
I'm afraid it won't work with log4j2-core:2.8.1. Could you try to upgrade Log4j2 to 2.11+?

**Comment by ForceUpdate1** [comment]
Unfortunately this is not possible, because the version of Minecraft is fixed

**Comment by ForceUpdate1** [comment]
I found the problem. The problem is that the classes of Log4J are loaded in the MinecraftServer classloader and the fix does not work with the package so that they are loaded in the plugin classloader. Is there any way around this fix?

**Comment by ForceUpdate1** [comment]
https://github.com/rfoltyns/log4j2-elasticsearch/blob/40d8c4e4c6c919093cf1de3c42c8476162bda7f5/log4j2-elasticsearch-core/src/main/java/org/apache/logging/log4j/core/jackson/ExtendedLog4j2JsonModule.java#L1

**Comment by rfoltyns** [comment]
Try the `JsonLayout`. It's the basic one from log4j-core. 
You won't able to use object pooling though.
Also, different `IndexTemplate` may be required to ingest the data.

**Comment by ForceUpdate1** [comment]
`[13:57:38 ERROR]: [org.bukkit.craftbukkit.v1_15_R1.CraftServer] com/fasterxml/jackson/databind/ser/FilterProvider initializing ElasticSearchAppender v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:896) ~[patched_1.15.1.jar:git-Paper-48]
at org.apache.logging.log4j.core.layout.JsonLayout$Builder.build(JsonLayout.java:838) ~[patched_1.15.1.jar:git-Paper-48]
at de.cytooxien.elasticsearch.ElasticSearchPlugin.createElasticsearchAppenderBuilder(ElasticSearchPlugin.java:134) ~[?:?]
at de.cytooxien.elasticsearch.ElasticSearchPlugin.onLoad(ElasticSearchPlugin.java:63) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:361) ~[patched_1.15.1.jar:git-Paper-48]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.15.1.jar:git-Paper-48]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-48]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.FilterProvider
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
... 8 more`

**Comment by ForceUpdate1** [comment]
I think I found a solution.
I simply take the layout of the File Appender from the MinecraftServer

        <RollingRandomAccessFile name="File" fileName="logs/latest.log" filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz">
            <PatternLayout>
                <LoggerNamePatternSelector defaultPattern="[%d{HH:mm:ss}] [%t/%level]: [%logger] %minecraftFormatting{%msg}{strip}%n">
                    
                    
                    <PatternMatch key=",net.minecraft.,Minecraft,com.mojang.,com.sk89q.,ru.tehkode.,Minecraft.AWE"
                                  pattern="[%d{HH:mm:ss}] [%t/%level]: %minecraftFormatting{%msg}{strip}%n" />
                </LoggerNamePatternSelector>
            </PatternLayout>
            <Policies>
                <TimeBasedTriggeringPolicy />
                <OnStartupTriggeringPolicy />
            </Policies>
            <DefaultRolloverStrategy max="1000"/>
        </RollingRandomAccessFile>


Now no exception is thrown.
The problem now is that nothing happens. 
For example, if I call logger#info, it appears in the log file, but not in elastic. There is also no index for it.

    public void onLoad() {
        instance = this;

        Logger logger = MinecraftServer.LOGGER;
        org.apache.logging.log4j.core.Logger coreLogger = (org.apache.logging.log4j.core.Logger)logger;
        createLoggerProgrammatically(coreLogger, createElasticsearchAppenderBuilder(coreLogger, false), Configuration::getAsyncLoggerConfigDelegate);
        logger.info("test message");
    }


    public  ElasticsearchAppender.Builder createElasticsearchAppenderBuilder(org.apache.logging.log4j.core.Logger coreLogger, boolean messageOnly) {

        JestHttpObjectFactory.Builder jestHttpObjectFactoryBuilder;
        jestHttpObjectFactoryBuilder = JestHttpObjectFactory.newBuilder();

        jestHttpObjectFactoryBuilder.withConnTimeout(1000)
                .withReadTimeout(10000)
                .withIoThreadCount(8)
                .withDefaultMaxTotalConnectionPerRoute(8)
                .withMaxTotalConnection(8)
                .withMappingType("_doc");

        jestHttpObjectFactoryBuilder.withServerUris(hostname);

        IndexTemplate indexTemplate = new IndexTemplate.Builder()
                .withName("log4j2_test_jest")
                .withSource(loadClasspathResource("classpath:indexTemplate.json"))
                .build();

        BatchDelivery asyncBatchDelivery = new SpigotAsyncBatchDelivery(BATCH_SIZE + ADDITIONAL_BATCH_SIZE, 1000, jestHttpObjectFactoryBuilder.build(), AsyncBatchDelivery.Builder.DEFAULT_FAILOVER_POLICY, indexTemplate);

        IndexNameFormatter indexNameFormatter = RollingIndexNameFormatter.newBuilder()
                .withIndexName("log4j2_test_jest")
                .withPattern("yyyy-MM-dd-HH")
                .build();

        return ElasticsearchAppender.newBuilder()
                .withName("elastic-appender")
                .withMessageOnly(messageOnly)
                .withBatchDelivery(asyncBatchDelivery)
                .withIndexNameFormatter(indexNameFormatter)
                .withLayout((AbstractLayout) coreLogger.getContext().getConfiguration().getAppender("File").getLayout())
                .withIgnoreExceptions(false);
    }

    public void createLoggerProgrammatically(org.apache.logging.log4j.core.Logger coreLogger, ElasticsearchAppender.Builder appenderBuilder, Function<Configuration, AsyncLoggerConfigDelegate> delegateSupplier) {

        LoggerContext ctx = coreLogger.getContext();

        final Configuration config = ctx.getConfiguration();

        Appender appender = appenderBuilder.build();
        appender.start();

        ((LifeCycle2)delegateSupplier.apply(config)).start();

        config.addAppender(appender);
    }

    public class SpigotAsyncBatchDelivery extends AsyncBatchDelivery {

        public SpigotAsyncBatchDelivery(int batchSize, int deliveryInterval, ClientObjectFactory objectFactory, FailoverPolicy failoverPolicy, IndexTemplate indexTemplate) {
            super(batchSize, deliveryInterval, objectFactory, failoverPolicy, indexTemplate);
        }

        @Override
        protected BatchEmitterServiceProvider createBatchEmitterServiceProvider() {
            return new SpigotBatchEmitterServiceProvider();
        }
    }

    public class SpigotBatchEmitterServiceProvider extends BatchEmitterServiceProvider{

        private final Logger LOG = StatusLogger.getLogger();

        @Override
        public BatchEmitter createInstance(int batchSize, int deliveryInterval, ClientObjectFactory clientObjectFactory, FailoverPolicy failoverPolicy) {
            BatchEmitterFactory factory = new BulkEmitterFactory(); //Service#load not supported
            LOG.info("BatchEmitterFactory class found {}", factory.getClass().getName());
            if (factory.accepts(clientObjectFactory.getClass())) {
                LOG.info("Using {} as BatchEmitterFactoryProvider", factory);
                return factory.createInstance(batchSize, deliveryInterval, clientObjectFactory, failoverPolicy);
            }
            throw new ConfigurationException(String.format("No compatible BatchEmitter implementations for %s found", clientObjectFactory.getClass().getName()));
        }
    }

I hope you can help me

**Comment by ForceUpdate1** [comment]
[15:06:06 INFO]: [io.searchbox.client.AbstractJestClient] Setting server pool to a list of 1 servers: [http://localhost:9200]
[15:06:06 INFO]: [io.searchbox.client.JestClientFactory] Using multi thread/connection supporting pooling connection manager
[15:06:06 INFO]: [io.searchbox.client.JestClientFactory] Using default GSON instance
[15:06:06 INFO]: [io.searchbox.client.JestClientFactory] Node Discovery disabled...
[15:06:06 INFO]: [io.searchbox.client.JestClientFactory] Idle connection reaping disabled...
[15:06:06 WARN]: log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
[15:06:06 WARN]: log4j:WARN Please initialize the log4j system properly.
[15:06:06 WARN]: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2020-01-22 15:06:07,042 I/O dispatcher 1 WARN One or more of the items in the Bulk request failed, check BulkResult.getItems() for more information.
2020-01-22 15:06:07,044 I/O dispatcher 1 WARN Batch of 1 items failed. Redirecting to org.appenders.log4j2.elasticsearch.NoopFailoverPolicy

**Comment by ForceUpdate1** [comment]
This is the error message that is thrown

`{ 
   "took":2,
   "errors":true,
   "items":[ 
      { 
         "index":{ 
            "_index":"log4j2_test_jest-2020-01-22-15",
            "_type":"_doc",
            "_id":"dXm8zW8BxM6rA-JRNqoN",
            "status":400,
            "error":{ 
               "type":"mapper_parsing_exception",
               "reason":"failed to parse",
               "caused_by":{ 
                  "type":"not_x_content_exception",
                  "reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"
               }
            }
         }
      }
   ]
}
`
Log Line: " [15:51:03] [Server thread/INFO]: Found new data pack vanilla, loading it automatically"

`{
  "index_patterns": [
    "log4j2*"
  ],
  "settings": {
    "index": {
      "refresh_interval": "5s"
    }
  },
  "mappings": {
    "properties": {
      "loggerName": {
        "type": "keyword",
        "index": false
      },
      "message": {
        "type": "keyword",
        "index": false
      },
      "timeMillis": {
        "type": "date",
        "format": "epoch_millis"
      },
      "thread": {
        "type": "keyword",
        "index": false
      },
      "level": {
        "type": "keyword",
        "index": false
      }
    }
  }
}`

**Comment by rfoltyns** [comment]
You're getting `not_x_content_exception` because `PatternLayout` doesn't produce a valid JSON. 
Have you tried adding Jackson dependencies to the classpath while using `JsonLayout`? If that doesn't work other options are:
* creating your own Minecraft server build with all deps included
* writing your own, Gson based layout (I've found Gson embedded in Minecraft uber-jar)
* writing to a file and using Logstash

**Comment by rfoltyns** [comment]
Closed due to lack of activity
